config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  
  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index], format: :json do
        resources :comments, only: [:index, :create], format: :json
      end
    end
  end

  mount SwaggerUiEngine::Engine, at: '/swagger'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define abilities for the user here. For example:
    if user.is? :admin
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author: user
      can :manage, Comment, author: user
    end
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post'

  after_save :update_counter

  def update_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post'

  after_save :update_counter

  def update_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_default_values

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  after_save :update_counter

  def update_counter
    author.update(posts_counter: author.posts.count)
  end

  def five_recent_comments
    comments.limit(5).order(created_at: :DESC)
  end

  private

  def set_default_values
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :set_default_values
  attr_accessor :email_confirmation

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :email, confirmation: { case_sensitive: false }

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  ROLES = %i[admin default].freeze

  def three_recent_posts
    posts.limit(3).order(created_at: :DESC)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end

  def set_default_values
    self.posts_counter ||= 0
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  before_action :set_user, only: %i[index create]
  before_action :set_post, only: %i[index create]

  def index
    comments = @post.comments
    render json: comments, status: :ok
  end

  def create
    comment = @post.comments.build(comment_params)
    comment.author = @user
    comment.text = comment_params[:text]
    if comment.save
      render json: comment, status: :created, except: [:created_at, :updated_at]
    else
      render json: { errors: comment.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  before_action :set_user

  def index
    posts = Post.where(author_id: @user.id)
    render json: posts, status: :ok
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name posts_counter email_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(post: @post)
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params.merge(post: @post))

    if @comment.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.destroy
    post.decrement!(:comments_counter)
    redirect_to user_post_path(post.author, post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
# class LikesController < ApplicationController
#   def create
#     @post = Post.find(params[:post_id])
#     @like = current_user.likes.build(post: @post)

#     if @like.save
#       redirect_to user_post_path(@post.author, @post)
#     else
#       render :new
#     end
#   end

#   private

#   def like_params
#     params.require(:like).permit(:post_id)
#   end
# end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
  end

  def show
    @post = Post.includes(:author).find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = @post.author
    @post.destroy
    user.decrement!(:posts_counter)
    redirect_to user_path(user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'standard'
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with(model: [@post.author, @comment], url: user_post_comments_path(@post.author, @post), local: true) do |f| %>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  
  <%= f.hidden_field :post_id, value: @post.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Blog App</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body>
      <div id = "container">
         <%= yield -%>
      </div>
   </body>
   
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/_comment.html.erb
<% unless comments.empty? %>
  <div class='comment'>
    <% comments.includes(:author).each do |comment| %>
      <div class='delete-comment'>
        Username: <%= comment.author.name %>
        Comment: <%= comment.text %>
        <% if can? :destroy, comment %>
   <%= button_to 'Delete', url_for([comment.post.author, comment.post, comment]), method: :delete %>
 <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% if @posts.empty?%>
<p>No posts to display</p>
<%else%>
<%= render partial: "users/username", locals: { user: @posts[0].author} %>
<ul class='user-posts'>
<% @posts.each_with_index do |post| %>
  <li>
  <%link = "posts/#{post.id}"%>
  <a href=<%=link%>>
  <h3><%=post.title%></h3>
  <h4>Post #<%=post.id%></h4>
  <p><%=post.text%></p>
  <span>Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter%></span>
  </a>
  </li>
  <%= render partial: "comment", locals: {comments: post.five_recent_comments} %>
<% end %>
<button>Pagination</button>
<%= link_to "Create a new post", new_user_post_path(current_user) %>
</ul>
<%end%>

app/views/posts/new.html.erb
<%# <% <%= form_with(model: [current_user, @post], local: true) do |f| %> 
  <%# <div class="field"> %>
    <%# <%= f.label :title %> 
    <%# <%= f.text_field :title %> 
  <%# </div> %>
  <%# <div class="field"> %>
    <%# <%= f.label :text %> 
    <%# <%= f.text_area :text %> 
  <%# </div> %>
  <%# <div class="actions"> %>
    <%# <%= f.submit %> 
  <%# </div> %>
<%# <% end %>  

app/views/posts/show.html.erb
  <div class='single-post'>
  <h3><%=@post.title%></h3>
  <h4>Post #<%=@post.id%> by <%=@post.author.name%></h4>
  <span>Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter%></span>
  <p><%=@post.text%></p>
  </div>
  <%= render partial: 'comment', locals: { comments: @post.comments } %>
  <%= link_to 'Add a comment', new_user_post_comment_path(current_user, @post) %>
  <span>
  <%= button_to 'Like', user_post_likes_path(current_user, @post), method: :post %>
  <% if can? :destroy, @post %>
  <%= button_to "delete", user_post_path(current_user.id, @post.id), class: "btn btn-danger btn-sm", method: :delete %>
  <% end %>
  </span>

app/views/users/_username.html.erb
<div class='username'>
<img src='https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80' alt='user photo'>
<div class="content"><h3><%= user.name%></h3><h4>Number of posts: <%= user.posts_counter%></h4></div>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
  Logged in as <%= current_user.email %>.
  <div><%= link_to 'Edit profile', edit_user_registration_path %></div>
  <div><%= button_to 'Sign out', destroy_user_session_path, method: :delete %></div> 
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
<ul class='users-list'>
<% @users.each do |user| %>
  <li>
  <%link = "users/#{user.id}"%>
  <a href=<%=link%>>
<%= render partial: "username", locals: { user: user } %>
</a>
</li>
<% end %>
</ul>

app/views/users/show.html.erb
<%= render partial: "username", locals: { user: @user } %>
<div>
<h3>Bio</h3>
<p><%=@user.bio%></p>
</div>
<ul class='user-posts'>
<% @user.three_recent_posts.each_with_index do |post| %>
  <li>
  <a  href=<%="#{@user.id}/posts/#{post.id}"%>><%=post.title%></a>
  <h4>Post #<%=post.id%></h4>
  <p><%=post.text%></p>
  <% if can? :destroy, post %>
  <%= button_to "delete", user_post_path(current_user.id, post.id), class: "btn btn-danger btn-sm", method: :delete %>
  <% end %>
  <span>Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter%></span>
  </li>
<% end %>
<%link = "#{@user.id}/posts"%>
<button><a href=<%=link%>>Show All Posts</a></button>
</ul>